queue_rules:
  - name: default
    update_method: rebase
    update_bot_account: jjrawlins
    queue_conditions:
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
      - status-success=package-python
      - status-success=package-go
      - status-success=package-dotnet
      - author=projenbuildmanager[bot]
    merge_method: squash
    autosquash: true
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body }}
    autoqueue: true
  - name: Auto-merge dependency upgrade PRs Constructs
    update_bot_account: jjrawlins
    queue_conditions:
      - head=github-actions/upgrade-main
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
      - status-success=package-python
      - status-success=package-go
      - status-success=package-dotnet
    update_method: rebase
    merge_method: squash
    autoqueue: true
  - name: Auto-merge dependency upgrade PRs CDK Stacks
    update_method: rebase
    update_bot_account: jjrawlins
    queue_conditions:
      - head=github-actions/upgrade
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
      - status-success=package-python
      - status-success=package-go
      - status-success=package-dotnet
    autoqueue: true
    autosquash: true
  - name: Queue PRs with approved label
    update_bot_account: jjrawlins
    queue_conditions:
      - label=approved
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
      - status-success=package-python
      - status-success=package-go
      - status-success=package-dotnet
      - author=jjrawlins
    update_method: rebase
    autoqueue: true
    autosquash: true
pull_request_rules:
  - name: Automatic merge on approval and passing checks
    description: Rules for process pull requests
    conditions:
      - "#approved-reviews-by >= 1" 
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=package-js
      - status-success=package-python
      - status-success=package-go
      - status-success=package-dotnet
      - -author=jjrawlins
      - approved-reviews-by=jjrawlins
      - or:
          - label~=(do-not-merge)
          - label=approved
          - author=jjrawlins
          - status-success=build
          - status-success=package-js
          - status-success=package-python
          - status-success=package-go
          - status-success=package-dotnet
      - or:
          - label~=(do-not-merge)
          - author=projenbuildmanager[bot]
          - status-success=build
          - status-success=package-js
          - status-success=package-python
          - status-success=package-go
          - status-success=package-dotnet
          - head=github-actions/upgrade
          - or:
              - head=github-actions/upgrade-main

    actions:
      merge:
        method: squash
      delete_head_branch:
      rebase:
        
    
merge_queue:
  max_parallel_checks: 1
