import { awscdk, TextFile, YamlFile, DependencyType } from 'projen';
import { Dependabot, DependabotScheduleInterval, GithubCredentials, VersioningStrategy } from 'projen/lib/github';
import { NpmAccess } from 'projen/lib/javascript';

const cdkVersion = '2.85.0';
const minConstructsVersion = '10.0.5';
const devConstructsVersion = '10.0.5';
const cdkCliVersion = '2.1029.2';
const devNodeVersion = '20.19.0';
const minNodeVersion = '20.0.0';
const workflowNodeVersion = '24.x';
const minProjenVersion = '0.99.52';

const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Jayson Rawlins',
  authorAddress: 'JaysonJ.Rawlins@gmail.com',
  packageName: '@jjrawlins/cdk-iam-policy-builder-helper',
  description: 'A CDK construct that helps build IAM policies using the AWS IAM Policy Builder dump. Normally it is better to use cdk-iam-floyd, However, I found that cdk-iam-floyd currently is not jsii compliant so I wasn\'t able to use it in my jsii compliant projects in languages that are not typescript or python.',
  keywords: ['aws', 'cdk', 'iam-actions', 'iam-policy'],
  repositoryUrl: 'https://github.com/JaysonRawlins/cdk-iam-policy-builder-helper.git',
  defaultReleaseBranch: 'main',
  license: 'Apache-2.0',
  minNodeVersion: minNodeVersion,
  workflowNodeVersion: workflowNodeVersion,
  cdkVersion: cdkVersion,
  cdkCliVersion: cdkCliVersion,
  projenVersion: minProjenVersion,
  projenrcTs: true,
  name: '@jjrawlins/cdk-iam-policy-builder-helper',
  stability: 'stable',

  peerDeps: [
    `aws-cdk-lib@>=${cdkVersion} <3.0.0`,
    `constructs@>=${minConstructsVersion} <11.0.0`,
  ],
  deps: [
    '@aws-sdk/client-iam',
    'jsonc-parser',
  ],
  bundledDeps: [
    '@aws-sdk/client-iam',
    'jsonc-parser',
  ],
  devDeps: [
    `aws-cdk@${cdkCliVersion}`,
    `aws-cdk-lib@${cdkVersion}`,
    '@aws-sdk/types',
    '@types/node',
  ],

  releaseToNpm: true,
  npmAccess: NpmAccess.PUBLIC,
  npmTrustedPublishing: true,

  publishToPypi: {
    distName: 'jjrawlins-cdk-iam-policy-builder-helper',
    module: 'jjrawlins_cdk_iam_policy_builder_helper',
    trustedPublishing: true,
  },
  publishToNuget: {
    dotNetNamespace: 'JJRawlins.CdkIamPolicyBuilderHelper',
    packageId: 'JJRawlins.CdkIamPolicyBuilderHelper',
    trustedPublishing: true,
  },
  publishToGo: {
    moduleName: 'github.com/jaysonrawlins/cdk-iam-policy-builder-helper',
    packageName: 'cdkiampolicybuilderhelper',
  },

  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: 'PROJEN_APP_ID',
      privateKeySecret: 'PROJEN_APP_PRIVATE_KEY',
    }),
    mergify: false,
    pullRequestLintOptions: {
      semanticTitleOptions: {
        types: ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'revert', 'ci', 'build', 'deps', 'wip', 'release'],
      },
    },
  },

  depsUpgrade: false,
  buildWorkflowOptions: {
    mutableBuild: false,
  },

  workflowBootstrapSteps: [
    {
      name: 'Install Aikido Safe-Chain 1.5.3 (in-flight malware scanner, 7d minimum age)',
      run: [
        'echo "SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS=168" >> $GITHUB_ENV',
        'curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.5.3/install-safe-chain.sh | sh -s -- --ci',
      ].join('\n'),
    },
  ],

  gitignore: [
    'methods_list.txt',
    'cdkiampolicybuilderhelper/',
    '.dccache',
    '.yalc',
  ],
});

project.package.addField('resolutions', {
  'brace-expansion': '1.1.12',
  '@eslint/plugin-kit': '^0.3.4',
  'eslint-import-resolver-typescript': '^4.4.4',
  'aws-cdk-lib': `>=${cdkVersion} <3.0.0`,
  'constructs': devConstructsVersion,
  // Exact-pin packages whose latest versions are inside Aikido Safe-Chain's
  // 7-day cooldown window. Each pinned version was the latest stable as of
  // 2026-05-14 (today minus 7 days). Bump as the cooldown clears upstream.
  // Yarn 1 resolutions need the **/ glob to override transitive ranges, not
  // just direct requests.
  'projen': minProjenVersion,
  'jsii': '5.9.40',
  'jsii-rosetta': '5.9.45',
  '@jsii/check-node': '1.129.0',
  '@jsii/spec': '1.129.0',
  'semver': '7.8.0',
});

project.package.addField('engines', {
  node: `>=${minNodeVersion}`,
});

project.deps.removeDependency('constructs');
project.deps.addDependency(`constructs@>=${minConstructsVersion} <11.0.0`, DependencyType.PEER);

new TextFile(project, '.tool-versions', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    `nodejs ${devNodeVersion}`,
    'yarn 1.22.22',
  ],
});

project.eslint?.addOverride({
  files: ['src/**/*.ts'],
  rules: {
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
      peerDependencies: true,
    }],
  },
});

project.compileTask.exec('rm -f tsconfig.json');

// Custom tasks ported from the pre-projen package.json
project.addTask('generate:actions', {
  description: 'Download IAM actions definitions from AWS and regenerate Actions.ts',
  exec: 'set -eu && ts-node -P tsconfig.dev.json ./src/bin/download-actions-json.ts && ts-node -P tsconfig.dev.json ./src/bin/create-actions-json.ts && yarn eslint && echo "Actions.ts created successfully"',
});

project.addTask('generate:managed-policies', {
  description: 'Download IAM managed policies from AWS and regenerate ManagedPolicies.ts',
  exec: 'set -eu && ts-node -P tsconfig.dev.json ./src/bin/download-managed-policies-json.ts && yarn eslint && echo "ManagedPolicies.ts created successfully"',
});

// projen already creates a `compat` task; override its body to use our .compatignore.
project.removeTask('compat');
project.addTask('compat', {
  description: 'jsii API compatibility check against the published version',
  exec: 'jsii-diff npm:$(node -p "require(\'./package.json\').name") -k --ignore-file .compatignore || (echo "\\nUNEXPECTED BREAKING CHANGES: add keys to .compatignore to skip.\\n" && exit 1)',
});

// =========================================================================
// Security baseline — see ../.claude/projen-security-baseline.ts.
// =========================================================================

const prLintWorkflow = project.github!.tryFindWorkflow('pull-request-lint');
if (prLintWorkflow) {
  prLintWorkflow.file!.addOverride(
    'jobs.validate.steps.0.uses',
    'amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50', // v6.1.1
  );
}

const dependabot = new Dependabot(project.github!, {
  scheduleInterval: DependabotScheduleInterval.WEEKLY,
  versioningStrategy: VersioningStrategy.LOCKFILE_ONLY,
  labels: ['dependencies'],
  openPullRequestsLimit: 10,
  cooldown: {
    defaultDays: 7,
    semverMinorDays: 7,
    semverPatchDays: 3,
    include: ['*'],
  },
  groups: {
    'aws-sdk': { patterns: ['@aws-sdk/*', '@smithy/*'] },
    'typescript-eslint': { patterns: ['@typescript-eslint/*'] },
  },
});

dependabot.config.updates[0].ignore = [
  { 'dependency-name': 'projen' },
  { 'dependency-name': '*', 'update-types': ['version-update:semver-major'] },
];

dependabot.config.updates.push({
  'package-ecosystem': 'github-actions',
  'directory': '/',
  'schedule': { interval: 'weekly' },
  'open-pull-requests-limit': 0,
  'labels': ['dependencies', 'github-actions'],
});

new YamlFile(project, '.github/workflows/security.yml', {
  obj: {
    name: 'security',
    on: { pull_request: {}, workflow_dispatch: {} },
    jobs: {
      security: { uses: 'JaysonRawlins/.github/.github/workflows/security.yml@main' },
    },
  },
});

new YamlFile(project, '.github/workflows/semgrep.yml', {
  obj: {
    name: 'Semgrep',
    on: {
      push: { branches: ['main'] },
      pull_request: { branches: ['main'] },
    },
    permissions: { 'contents': 'read', 'security-events': 'write' },
    jobs: {
      scan: {
        'name': 'Scan',
        'runs-on': 'ubuntu-latest',
        'container': {
          image: 'semgrep/semgrep@sha256:9349edbadf90c3f3c0c3f55867625354e89680e6fa10d9034042af52fdb0e0d0',
        },
        'steps': [
          { uses: 'actions/checkout@v4' },
          {
            name: 'Run Semgrep',
            run: [
              'semgrep scan \\',
              '  --config=p/security-audit \\',
              '  --config=p/typescript \\',
              '  --config=p/javascript \\',
              '  --config=p/nodejs \\',
              '  --sarif --output=semgrep.sarif \\',
              '  || true',
            ].join('\n'),
          },
          {
            'name': 'Upload SARIF',
            'if': "always() && hashFiles('semgrep.sarif') != ''",
            'continue-on-error': true,
            'uses': 'github/codeql-action/upload-sarif@f411752efdf656cb71aa17b755b22c890960da1d', // v3.35.5
            'with': { sarif_file: 'semgrep.sarif' },
          },
        ],
      },
    },
  },
});

new YamlFile(project, '.github/workflows/dependabot-automerge.yml', {
  obj: {
    name: 'dependabot-automerge',
    on: {
      pull_request_target: {
        types: ['opened', 'synchronize', 'reopened', 'ready_for_review'],
      },
    },
    permissions: { 'contents': 'write', 'pull-requests': 'write' },
    jobs: {
      automerge: {
        'runs-on': 'ubuntu-latest',
        'if': "github.actor == 'dependabot[bot]'",
        'steps': [
          {
            name: 'Get Dependabot metadata',
            id: 'metadata',
            uses: 'dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a', // v2.5.0
            with: { 'github-token': '${{ secrets.GITHUB_TOKEN }}' },
          },
          {
            name: 'Enable auto-merge for safe Dependabot PRs',
            if: "steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'",
            run: 'gh pr merge --auto --squash "$PR_URL"',
            env: {
              PR_URL: '${{ github.event.pull_request.html_url }}',
              GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
            },
          },
        ],
      },
    },
  },
});

new YamlFile(project, '.github/workflows/dependabot-rebase-stuck.yml', {
  obj: {
    name: 'dependabot-unblocker',
    on: {
      schedule: [{ cron: '0 9 * * 1' }],
      workflow_dispatch: {},
    },
    permissions: { 'pull-requests': 'read', 'actions': 'write' },
    jobs: {
      unblock: {
        'runs-on': 'ubuntu-latest',
        'steps': [
          {
            name: 'Rerun failed build on Aikido-cooldown-blocked Dependabot PRs',
            env: {
              GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
              REPO: '${{ github.repository }}',
            },
            run: [
              'set -euo pipefail',
              '',
              'stuck=$(gh pr list --repo "$REPO" \\',
              '  --author "app/dependabot" \\',
              '  --state open \\',
              '  --json number,statusCheckRollup \\',
              '  --jq \'.[] | select([.statusCheckRollup[] | select(.name == "build")] | any(.conclusion == "FAILURE")) | .number\')',
              '',
              'if [ -z "$stuck" ]; then',
              '  echo "No stuck Dependabot PRs."',
              '  exit 0',
              'fi',
              '',
              'for pr in $stuck; do',
              '  run_id=$(gh pr view "$pr" --repo "$REPO" --json statusCheckRollup \\',
              '    --jq \'.statusCheckRollup[] | select(.name == "build") | .detailsUrl\' \\',
              '    | grep -oE "/runs/[0-9]+" | head -1 | cut -d/ -f3)',
              '',
              '  if [ -z "$run_id" ]; then',
              '    echo "PR #$pr: no build run id, skipping"',
              '    continue',
              '  fi',
              '',
              '  log=$(gh run view "$run_id" --repo "$REPO" --log-failed 2>&1 || true)',
              '',
              '  if echo "$log" | grep -q "minimum package age"; then',
              '    echo "PR #$pr: Aikido cooldown block — rerunning failed build (preserves lockfile)"',
              '    gh run rerun "$run_id" --repo "$REPO" --failed',
              '  elif echo "$log" | grep -q "Safe-chain: blocked"; then',
              '    echo "PR #$pr: Aikido blocked (non-age, possibly malware) — leaving for human review"',
              '  else',
              '    echo "PR #$pr: build failed for unrecognized reason — leaving for human review"',
              '  fi',
              'done',
            ].join('\n'),
          },
        ],
      },
    },
  },
});

const releaseWorkflow = project.github!.tryFindWorkflow('release')!;
releaseWorkflow.file!.addOverride('jobs.release.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.0.with.node-version', '24');
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.4.run', 'cd .repo && yarn install --check-files --frozen-lockfile --ignore-engines');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.steps.0.with.node-version', workflowNodeVersion);
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.steps.0.with.node-version', workflowNodeVersion);
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.0.with.node-version', workflowNodeVersion);

project.synth();
