name: PR Test
on:
  workflow_dispatch: {}
jobs:
  create-token:
    name: Create Token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.create_token.outputs.token }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      packages: write
    steps:
      - name: Create Token
        id: create_token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.PROJEN_APP_ID }}
          private-key: ${{ secrets.PROJEN_APP_PRIVATE_KEY }}

